name: Deploy to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Start SSH agent & add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to Hetzner server
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            ./ \
            ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }}:${{ secrets.REMOTE_PATH }}

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} << 'EOF'
            cd "${{ secrets.REMOTE_PATH }}" || exit 1
            # Ensure latest images & recreate containers
            docker-compose pull
            docker-compose up -d --build
          EOF
